################################################
### DO NOT EDIT THIS FILE WITHOUT PERMISSION ###
################################################
# This file contains all necessary tools for calling c functions (their result)
# from the python module.

import ctypes
from ctypes import *

def get_int_result (file_path, *arg):
    so_file = file_path
    c_call = CDLL(so_file)
    c_return = c_call.mesaj1(arg[1]);
    return c_return

def get_str_result(file_path):
    so_file = ctypes.cdll.LoadLibrary(file_path)
    so_file.mesaj.restype = ctypes.c_char_p # override the default return type (int)
    result = so_file.mesaj()
    print ctypes.c_char_p(result).value



#print (get_int_result("../../../out/so_files/test.so", 10, 11))
get_str_result("../../../out/so_files/test.so")
